#!/bin/bash
#
#

REV=$(git describe --always --long --dirty --broken --tags)
SRC=$(git config --get remote.origin.url)
NOW_UTC=$(/bin/date -u '+%Y-%m-%dT%H:%M:%SZ')
docker build docker \
	--label "org.opencontainers.image.revision=${REV}" \
	--label "org.opencontainers.image.source=${SRC}" \
	--label "org.opencontainers.image.created=${NOW_UTC}" \
	-t labwork
