#!/usr/bin/python3
#
# License: CC-0

import sys
import json
import requests

if len(sys.argv) < 3:
	print("syntax: %s [API endpoint URI] [assignment_name1] ([assignment_name2] ...)" % (sys.argv[0]))
	sys.exit(1)

user_id = "2e28d376-e06b-48b3-93b4-49b63e68be2d"
api_endpoint = sys.argv[1]
assignment_names = sys.argv[2:]

# Example handler for the "strcat" assignment
def handle_strcat(assignment):
	return " ".join(assignment["parts"])

# Example handler for "foobar" assignment
def handle_foobar(assignment):
	return { "foo": "bar" }

session = requests.Session()
for assignment_name in assignment_names:
	# Get the assignment
	result = session.get(api_endpoint + "/assignment/" + user_id + "/" + assignment_name)
	assert(result.status_code == 200)

	# See if we can compute the answer
	assignment = result.json()
	for testcase in assignment["testcases"]:
		if testcase["name"] == "strcat":
			response = handle_strcat(testcase["assignment"])
		elif testcase["name"] == "foobar":
			response = handle_foobar(testcase["assignment"])
		else:
			print("Do not know how to handle: %s" % (testcase["name"]))
			continue

		# We think we have an answer for this one, try to submit it
		result = session.post(api_endpoint + "/submission/" + testcase["tcid"], headers = {
			"Content-Type": "application/json",
		}, data = json.dumps(response))
		assert(result.status_code == 200)
		print(result.json())
